/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TiketBioskop.java
 *
 * Created on Jun 4, 2022, 9:21:01 PM
 */
package ticket.bioskop.pbo;

/**
 *
 * @author PC
 */
public class TiketBioskop1 extends javax.swing.JFrame {
    int reguler,sweetbox,platinum,premiere,harga,jumlah,total,beli,bayar,kembali;

    /** Creates new form TiketBioskop */
    public TiketBioskop1() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tayang = new javax.swing.JComboBox();
        rb_reguler = new javax.swing.JRadioButton();
        rb_platinum = new javax.swing.JRadioButton();
        txt_harga = new javax.swing.JTextField();
        rb_sweetbox = new javax.swing.JRadioButton();
        rb_premiere = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_total = new javax.swing.JTextField();
        txt_jumlah = new javax.swing.JTextField();
        txt_bayar = new javax.swing.JTextField();
        txt_kembalian = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btn_simpan = new javax.swing.JButton();

        jLabel11.setText("jLabel11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 255, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Jam Tayang :");

        jLabel2.setText("Jenis Tiket :");

        jLabel3.setText("Harga :");

        tayang.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih Jam Tayang", "15:00", "17:00", " " }));
        tayang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tayangActionPerformed(evt);
            }
        });

        rb_reguler.setText("Reguler");
        rb_reguler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_regulerActionPerformed(evt);
            }
        });

        rb_platinum.setText("Platinum");
        rb_platinum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_platinumActionPerformed(evt);
            }
        });

        rb_sweetbox.setText("SweetBox");
        rb_sweetbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_sweetboxActionPerformed(evt);
            }
        });

        rb_premiere.setText("Premiere");
        rb_premiere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_premiereActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_harga, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(rb_platinum, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                        .addGap(59, 59, 59))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(rb_reguler, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(rb_premiere, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rb_sweetbox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
                                .addGap(14, 14, 14)))
                        .addGap(70, 70, 70))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addComponent(tayang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(205, 205, 205))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tayang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rb_premiere)
                            .addComponent(rb_reguler))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rb_sweetbox)
                    .addComponent(rb_platinum))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 240));

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 14));
        jLabel4.setForeground(new java.awt.Color(102, 255, 102));
        jLabel4.setText("Jumlah Beli  :     ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 160, 38));

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 14));
        jLabel5.setForeground(new java.awt.Color(102, 255, 102));
        jLabel5.setText("Total Bayar :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 14));
        jLabel6.setForeground(new java.awt.Color(102, 255, 102));
        jLabel6.setText("Uang Bayar :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 14));
        jLabel7.setForeground(new java.awt.Color(102, 255, 102));
        jLabel7.setText("Kembalian  :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, -1, -1));

        txt_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totalActionPerformed(evt);
            }
        });
        getContentPane().add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 150, -1));

        txt_jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_jumlahActionPerformed(evt);
            }
        });
        txt_jumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_jumlahKeyReleased(evt);
            }
        });
        getContentPane().add(txt_jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 40, -1));

        txt_bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bayarActionPerformed(evt);
            }
        });
        txt_bayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_bayarKeyReleased(evt);
            }
        });
        getContentPane().add(txt_bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, 150, -1));
        getContentPane().add(txt_kembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 530, 150, -1));

        jLabel8.setFont(new java.awt.Font("Showcard Gothic", 3, 36));
        jLabel8.setText("BSI CINEMA TICKET");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 420, -1));

        btn_simpan.setBackground(new java.awt.Color(102, 255, 102));
        btn_simpan.setForeground(new java.awt.Color(51, 51, 255));
        btn_simpan.setText("SAVE");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        getContentPane().add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 90, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void txt_bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bayarActionPerformed
    bayar=Integer.parseInt(txt_bayar.getText());
    kembali=Integer.parseInt(txt_total.getText());
    total=bayar-harga;
    txt_kembalian.setText(String.valueOf(bayar));
}//GEN-LAST:event_txt_bayarActionPerformed

private void tayangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tayangActionPerformed
    if(tayang.getSelectedItem().equals("Pilih Jam Tayang")){
        buttonGroup2.clearSelection();
        txt_harga.setText("");
    }
    else if (tayang.getSelectedItem().equals("15:00")){
        reguler=30000;
        platinum=35000;
        sweetbox=45000;
        premiere=50000;
    }
    else if (tayang.getSelectedItem().equals("17:00")){
        reguler=30000;
        platinum=35000;
        sweetbox=45000;
        premiere=50000;
    }
}//GEN-LAST:event_tayangActionPerformed

private void rb_regulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_regulerActionPerformed
    if(rb_reguler.isSelected()){
        txt_harga.setText(String.valueOf(reguler));
    }
}//GEN-LAST:event_rb_regulerActionPerformed

private void rb_platinumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_platinumActionPerformed
 if(rb_platinum.isSelected()){
        txt_harga.setText(String.valueOf(platinum));
    }
}//GEN-LAST:event_rb_platinumActionPerformed

private void rb_sweetboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_sweetboxActionPerformed
 if(rb_sweetbox.isSelected()){
        txt_harga.setText(String.valueOf(sweetbox));
    }
}//GEN-LAST:event_rb_sweetboxActionPerformed

private void rb_premiereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_premiereActionPerformed
 if(rb_premiere.isSelected()){
        txt_harga.setText(String.valueOf(premiere));
    }
}//GEN-LAST:event_rb_premiereActionPerformed

private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
    this.setVisible(false);
       new ENJOY().setVisible(true);
}//GEN-LAST:event_btn_simpanActionPerformed

private void txt_jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_jumlahActionPerformed
    beli=Integer.parseInt(txt_jumlah.getText());
    harga=Integer.parseInt(txt_harga.getText());
    total=bayar*harga;
    txt_total.setText(String.valueOf(total));
}//GEN-LAST:event_txt_jumlahActionPerformed

private void txt_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txt_totalActionPerformed

private void txt_jumlahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_jumlahKeyReleased
 int a,b,c;
 a=Integer.valueOf(txt_harga.getText());
 b=Integer.valueOf(txt_jumlah.getText());
 c=a*b;
 txt_total.setText(""+c);
}//GEN-LAST:event_txt_jumlahKeyReleased

private void txt_bayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_bayarKeyReleased
int a,b,c;
 a=Integer.valueOf(txt_bayar.getText());
 b=Integer.valueOf(txt_total.getText());
 c=a-b;
 txt_kembalian.setText(""+c);
}//GEN-LAST:event_txt_bayarKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TiketBioskop1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TiketBioskop1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TiketBioskop1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TiketBioskop1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TiketBioskop1().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_simpan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton rb_platinum;
    private javax.swing.JRadioButton rb_premiere;
    private javax.swing.JRadioButton rb_reguler;
    private javax.swing.JRadioButton rb_sweetbox;
    private javax.swing.JComboBox tayang;
    private javax.swing.JTextField txt_bayar;
    private javax.swing.JTextField txt_harga;
    private javax.swing.JTextField txt_jumlah;
    private javax.swing.JTextField txt_kembalian;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
